name: Build Docker Image

on:
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: latest
  DB_USER: github
  DB_PASS: github
  DB_DATABASE: demo
  DB_URL: 'jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=UTC'
  
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.36
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ env.DB_DATABASE }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASS }}
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASS }}
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Setup maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: '24'
          java-distribution: 'corretto'
          cache-enabled: true
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          github-server-url: ${{ secrets.REPO_SERVER　}}
          repository: scott/demodd
          token: ${{ secrets.REPO_TOKEN　}}
        
      - name: Login registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: DB Migrate
        run: |       
          mvn flyway:migrate
        
      - name: JOOQ Genrate
        run: |    
          mvn jooq-codegen:generate
          
      - name: Build Docker image
        run: |
          mvn jooq-codegen:generate
          mvn spring-boot:build-image \
              -DskipTests \
              -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
              -Denv.DB_USER=$DB_USER \
              -Denv.DB_PASS=$DB_PASS \
              -Denv.DB_URL=$DB_URL
           
      - name: Push image to registry
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
