name: Unit Test

on:
  workflow_dispatch:
  
env:
  DB_USER: github
  DB_PASS: github
  DB_DATABASE: demo
  DB_URL: 'jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=UTC'
  
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.36
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ env.DB_DATABASE }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASS }}
          MYSQL_ROOT_PASSWORD: ${{ env.DB_PASS }}
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Setup maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: '24'
          java-distribution: 'corretto'
          cache-enabled: true
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          github-server-url: ${{ secrets.REPO_SERVER　}}
          repository: scott/demodd
          token: ${{ secrets.REPO_TOKEN　}}

      - name: DB Migrate
        run: |       
          mvn flyway:migrate
        
      - name: JOOQ Genrate
        run: |    
          mvn jooq-codegen:generate
        
      - name: Unit Test
        run: |
          mvn test
